name: rbd-epistasis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - scipy
  - statsmodels
  - scikit-learn
  - seaborn
  - openpyxl
  - networkx
  - jupyterlab
  - ipykernel
  - biopython
  - pyyaml
